services:
  postgres-db:
    image: postgres:16-alpine
    container_name: postgres-ninjas
    environment:
      POSTGRES_DB: cadastro_ninjas
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app-ninjas:
    build: .
    container_name: app-cadastro-ninjas
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/cadastro_ninjas
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - postgres-db

volumes:
  postgres_data: